
name: 'snowflake_demo'
version: '1.5.0'
config-version: 2
profile: 'default'
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

models:
  snowflake_demo:
    snowflake_sample_data:
      +materialized: view
